services:
  redis:
    image: "redis:alpine"
    command: redis-server --maxmemory 150mb --maxmemory-policy allkeys-lru

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --timeout 120 directory_listing.wsgi:application --no-sendfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  celery_general:
    build: .
    command: celery -A directory_listing worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery_xls:
    build: .
    command: celery -A directory_listing worker --loglevel=info --concurrency=1 --queues=xls_queue
    volumes:
      - .:/app
      - temp_volume:/app/tempfiles
    depends_on:
      - web
      - redis

volumes:
  static_volume:
  temp_volume:
