# Generated by Django 4.2.7 on 2024-01-27 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfig',
            name='url',
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='site_enable',
            field=models.BooleanField(default=True, verbose_name='Site Enable'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='template_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='website',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_names', models.TextField()),
                ('company_websites', models.TextField()),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_data', to='listing.apiconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.apiconfig')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
