# Generated by Django 4.2.7 on 2023-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='template_no',
            field=models.IntegerField(default=1),
        ),
    ]
