# Generated by Django 4.2.7 on 2024-02-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_companyurl_remove_apiconfig_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedata',
            name='api_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_data', to='listing.apiconfig'),
        ),
    ]
