# Generated by Django 4.2.7 on 2024-01-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_apiconfig_url_apiconfig_site_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_names', models.TextField()),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_data', to='listing.apiconfig')),
            ],
        ),
    ]
