# Generated by Django 4.2.7 on 2023-12-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_apiconfig_template_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
