# Generated by Django 4.2.7 on 2024-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_websitedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='website',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
