# Generated by Django 4.2.7 on 2024-02-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_generatedurl_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postedwebsite',
            name='website_name',
        ),
        migrations.AddField(
            model_name='postedwebsite',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.apiconfig'),
        ),
    ]
