# Generated by Django 4.2.7 on 2024-02-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_deletionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(max_length=1024)),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeletionResult',
        ),
    ]
