version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8001 --timeout 120 directory_listing.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  celery:
    build: .
    command: celery -A directory_listing worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  static_volume:
